const staff = [
  {
    id: 1,
    name: "Frank",
    title: "Owner/CEO",
    department: null,
    superior: null,
    skills: ["finances", "management"],
    flag: null,
  },
  {
    id: 2,
    name: "Roger",
    title: "Manager",
    department: "Marketing",
    superior: "Frank",
    skills: ["management", "marketing"],
    flag: "red",
  },
  {
    id: 3,
    name: "Charlie",
    title: "Graphic Designer",
    department: "Marketing",
    superior: "Roger",
    skills: ["Graphic Design"],
    flag: "green"
  },
  {
    id: 4,
    name: "Mac",
    title: "Manager",
    department: "Sales",
    superior: "Frank",
    skills: ["Sales", "Management"],
    flag: null,
  },
  {
    id: 5,
    name: "Dennis",
    title: "Salesperson",
    department: "Sales",
    superior: "Mac",
    skills: ["Sales"],
    flag: null,
  },
  {
    id: 6,
    name: "Dee",
    title: "Salesperson",
    department: "Sales",
    superior: "Mac",
    skills: ["Sales"],
  },
  {
    id: 7,
    name: "Jack",
    title: "Manager",
    department: "R&D",
    superior: "Frank",
    skills: ["Management", "Research", "Product Development"],
  },
  {
    id: 8,
    name: "Franklin",
    title: "Electrical Engineer",
    department: "R&D",
    superior: "Jack",
    skills: ["Research", "Product Development", "Electrical Engineering"],
  },
  {
    id: 9,
    name: "Antonio",
    title: "Software Developer",
    department: "R&D",
    superior: "Jack",
    skills: ["Research", "Product Development", "Software Development"],
  },
  {
    id: 10,
    name: "Brenda",
    title: "HR",
    department: "HR",
    superior: "Frank",
    skills: ["Human Resources"],
  },
  {
    id: 11,
    name: "Oscar",
    title: "Copywriter",
    department: "Marketing",
    superior: "Roger",
    skills: ["Writing", "Editing"],
  },
  {
    id: 12,
    name: "Geoffrey",
    title: "Product Designer",
    department: "R&D",
    superior: "Jack",
    skills: ["Product Design", "Graphic Design"],
  },
];

export default staff;